parameters:
    davamigo.translator.scanner.class:             Davamigo\TranslatorBundle\Model\Translator\Scanner
    davamigo.translator.storage.session.class:     Davamigo\TranslatorBundle\Model\Translator\Session\SessionStorage
    davamigo.translator.importer.excel.class:      Davamigo\TranslatorBundle\Model\Translator\Excel\ExcelImporter
    davamigo.translator.exporter.excel.class:      Davamigo\TranslatorBundle\Model\Translator\Excel\ExcelExporter
    davamigo.translator.exporter.yaml.class:       Davamigo\TranslatorBundle\Model\Translator\Yaml\YamlExporter
    davamigo.translator.file_creator.yaml.class:   Davamigo\TranslatorBundle\Model\Translator\Yaml\YamlFileCreator

services:
    davamigo.translator.scanner:
        class: "%davamigo.translator.scanner.class%"
        arguments:
            kernel: "@kernel"

    davamigo.translator.storage.session:
        class: "%davamigo.translator.storage.session.class%"
        arguments:
            session: "@session"

    davamigo.translator.importer.excel:
        class: "%davamigo.translator.importer.excel.class%"
        arguments:
            phpexcel: "@phpexcel"

    davamigo.translator.exporter.excel:
        class: "%davamigo.translator.exporter.excel.class%"
        arguments:
            phpexcel: "@phpexcel"

    davamigo.translator.exporter.yaml:
        class: "%davamigo.translator.exporter.yaml.class%"

    davamigo.translator.file_creator.yaml:
        class: "%davamigo.translator.file_creator.yaml.class%"
