parameters:
    ifraktal.translator.scanner.class:             Ifraktal\TranslatorBundle\Model\Translator\Scanner
    ifraktal.translator.storage.session.class:     Ifraktal\TranslatorBundle\Model\Translator\Session\SessionStorage
    ifraktal.translator.importer.excel.class:      Ifraktal\TranslatorBundle\Model\Translator\Excel\ExcelImporter
    ifraktal.translator.exporter.excel.class:      Ifraktal\TranslatorBundle\Model\Translator\Excel\ExcelExporter
    ifraktal.translator.exporter.yaml.class:       Ifraktal\TranslatorBundle\Model\Translator\Yaml\YamlExporter
    ifraktal.translator.file_creator.yaml.class:   Ifraktal\TranslatorBundle\Model\Translator\Yaml\YamlFileCreator

services:
    ifraktal.translator.scanner:
        class: "%ifraktal.translator.scanner.class%"
        arguments:
            kernel: "@kernel"

    ifraktal.translator.storage.session:
        class: "%ifraktal.translator.storage.session.class%"
        arguments:
            session: "@session"

    ifraktal.translator.importer.excel:
        class: "%ifraktal.translator.importer.excel.class%"
        arguments:
            phpexcel: "@phpexcel"

    ifraktal.translator.exporter.excel:
        class: "%ifraktal.translator.exporter.excel.class%"
        arguments:
            phpexcel: "@phpexcel"

    ifraktal.translator.exporter.yaml:
        class: "%ifraktal.translator.exporter.yaml.class%"

    ifraktal.translator.file_creator.yaml:
        class: "%ifraktal.translator.file_creator.yaml.class%"
